Update project.py
made changes to answers, list_answers and vote function - however list_answers need further review
Errors:  [ if int(answer["Id"]) != int(accId.get('AcceptedAnswerId')):            , not 'NoneType'
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType' ]